const std = @import("std");
const p = @import("root.zig");
const model = @import("layout-model");

fn value(writer: *std.Io.Writer, data: anytype) !void {
    try std.zon.stringify.serializeMaxDepth(data, .{ .whitespace = false }, writer, 32);
}
/// Pure generation: no compilation, callback execution, source writes or device operations.
/// Consumers must provide callback_N modules from the exact verified source snapshot.
pub fn generate(gpa: std.mem.Allocator, snapshot: p.snapshot.Snapshot, board: p.Board) ![]u8 {
    const identity = try p.snapshot.identity(gpa, snapshot, board);
    const doc = snapshot.document;
    var output: std.Io.Writer.Allocating = .init(gpa);
    errdefer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("// Generated by keymap-project schema 1. Regenerate explicitly; do not edit.\nconst core = @import(\"zigmkay\").core;\n");
    try writer.print("pub const key_count = {d};\npub const dimensions = core.KeymapDimensions{{ .key_count = key_count, .layer_count = {d} }};\n", .{ doc.key_ids.len, doc.layers.len });
    try writer.writeAll("pub const sides: [key_count]core.Side = ");
    try value(writer, board.sides);
    try writer.writeAll(";\npub const keymap = [_][key_count]?core.KeyDef{\n");
    for (doc.layers) |layer| {
        try writer.writeAll(".{");
        for (layer.actions) |action| {
            const lowered: ?model.KeyDef = if (action) |a| try p.lowerAction(doc, a) else null;
            try value(writer, lowered);
            try writer.writeAll(",");
        }
        try writer.writeAll("},\n");
    }
    try writer.writeAll("};\npub const combos = [_]core.Combo2Def{\n");
    for (doc.combos) |combo| {
        const lowered = model.Combo2Def{ .key_indexes = .{ try p.keyIndex(doc, combo.key_ids[0]), try p.keyIndex(doc, combo.key_ids[1]) }, .layer = try p.layerIndex(doc, combo.layer_id), .timeout = combo.timeout, .key_def = try p.lowerAction(doc, combo.action) };
        try value(writer, lowered);
        try writer.writeAll(",\n");
    }
    try writer.writeAll("};\npub const encoder_actions = [_]core.EncoderAction{\n");
    for (doc.encoders) |tap| {
        try value(writer, model.EncoderAction{ .tap = try p.lowerTap(doc, tap) });
        try writer.writeAll(",\n");
    }
    try writer.writeAll("};\n");
    if (doc.callbacks.len == 0) {
        try writer.writeAll("pub const custom_functions = core.CustomFunctions{};\n");
    } else {
        try writer.writeAll("fn on_event(event: core.ProcessorEvent, layers: *core.LayerActivations, output: *core.OutputCommandQueue) void {\n");
        for (doc.callbacks, 0..) |_, index| try writer.print("    if (@import(\"callback_{d}\").custom_functions.on_event) |handler| handler(event, layers, output);\n", .{index});
        try writer.writeAll("}\npub const custom_functions = core.CustomFunctions{ .on_event = on_event };\n");
    }
    try writer.writeAll("pub fn identity(comptime protocol: type) protocol.Identity {\n    return ");
    try value(writer, identity);
    try writer.writeAll(";\n}\n");
    return output.toOwnedSlice();
}
