const std = @import("std");
const p = @import("root.zig");
const model = @import("layout-model");

fn value(writer: *std.Io.Writer, data: anytype) !void {
    try std.zon.stringify.serializeMaxDepth(data, .{ .whitespace = false }, writer, 32);
}
/// Pure generation: no compilation, callback execution, source writes or device operations.
/// Consumers must provide callback_N modules from the exact verified source snapshot.
pub fn generate(gpa: std.mem.Allocator, snapshot: p.snapshot.Snapshot, board: p.Board) ![]u8 {
    try p.sources.verify(gpa, snapshot);
    const identity = try p.snapshot.identity(gpa, snapshot, board);
    const doc = snapshot.document;
    var output: std.Io.Writer.Allocating = .init(gpa);
    errdefer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("// Generated by keymap-project schema 1. Regenerate explicitly; do not edit.\nconst core = @import(\"zigmkay\").core;\n");
    try writer.writeAll("pub const snapshot_id: [32]u8 = ");
    try value(writer, try p.snapshot.projectDigest(gpa, snapshot, board));
    try writer.writeAll(";\n");
    try writer.print("pub const key_count = {d};\npub const dimensions = core.KeymapDimensions{{ .key_count = key_count, .layer_count = {d} }};\n", .{ doc.key_ids.len, doc.layers.len });
    try writer.writeAll("pub const sides: [key_count]core.Side = ");
    try value(writer, board.sides);
    try writer.writeAll(";\npub const keymap = [_][key_count]?core.KeyDef{\n");
    for (doc.layers) |layer| {
        try writer.writeAll(".{");
        for (layer.actions) |action| {
            const lowered: ?model.KeyDef = if (action) |a| try p.lowerAction(doc, a) else null;
            try value(writer, lowered);
            try writer.writeAll(",");
        }
        try writer.writeAll("},\n");
    }
    try writer.writeAll("};\npub const combos = [_]core.Combo2Def{\n");
    for (doc.combos) |combo| {
        const lowered = model.Combo2Def{ .key_indexes = .{ try p.keyIndex(doc, combo.key_ids[0]), try p.keyIndex(doc, combo.key_ids[1]) }, .layer = try p.layerIndex(doc, combo.layer_id), .timeout = combo.timeout, .key_def = try p.lowerAction(doc, combo.action) };
        try value(writer, lowered);
        try writer.writeAll(",\n");
    }
    try writer.writeAll("};\npub const encoder_actions = [_]core.EncoderAction{\n");
    for (doc.encoders) |tap| {
        try value(writer, model.EncoderAction{ .tap = try p.lowerTap(doc, tap) });
        try writer.writeAll(",\n");
    }
    try writer.writeAll("};\n");
    if (doc.callbacks.len == 0) {
        try writer.writeAll("pub const custom_functions = core.CustomFunctions{};\n");
    } else {
        try writer.writeAll("fn on_event(event: core.ProcessorEvent, layers: *core.LayerActivations, output: *core.OutputCommandQueue) void {\n");
        for (doc.callbacks, 0..) |_, index| try writer.print("    if (@import(\"callback_{d}\").custom_functions.on_event) |handler| handler(event, layers, output);\n", .{index});
        try writer.writeAll("}\npub const custom_functions = core.CustomFunctions{ .on_event = on_event };\n");
    }
    try writer.writeAll("pub fn identity(comptime protocol: type) protocol.Identity {\n    return ");
    try value(writer, identity);
    try writer.writeAll(";\n}\n");
    return output.toOwnedSlice();
}

pub const contract = @import("build_contract.zig");
/// Explicit export to an owned directory; existing differing files are never overwritten.
/// The manifest is the final commit marker. Consumers verify every listed digest.
pub fn write(gpa: std.mem.Allocator, io: std.Io, dir: std.Io.Dir, snapshot: p.snapshot.Snapshot, board: p.Board) !contract.Manifest {
    const source = try generate(gpa, snapshot, board);
    defer gpa.free(source);
    var arena: std.heap.ArenaAllocator = .init(gpa);
    defer arena.deinit();
    const a = arena.allocator();
    var files: std.ArrayList(contract.File) = .empty;
    const callbacks = try a.alloc(contract.Callback, snapshot.document.callbacks.len);
    for (snapshot.document.callbacks, 0..) |_, ci| {
        const entry = try p.profiles.callbackEntry(snapshot, ci);
        callbacks[ci] = .{ .entry = try std.fmt.allocPrint(a, "callback_{d}/{s}", .{ ci, entry }) };
    }
    for (snapshot.sources) |file| {
        const path = try std.fmt.allocPrint(a, "callback_{d}/{s}", .{ file.callback_index, file.path });
        try ownedWrite(gpa, io, dir, path, file.bytes);
        var hash: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(file.bytes, &hash, .{});
        try files.append(a, .{ .path = path, .digest = hash });
    }
    try ownedWrite(gpa, io, dir, "keymap.zig", source);
    var hash: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(source, &hash, .{});
    try files.append(a, .{ .path = "keymap.zig", .digest = hash });
    const manifest = contract.Manifest{ .version = contract.version, .snapshot_id = try p.snapshot.projectDigest(gpa, snapshot, board), .board_id = snapshot.document.board_id, .profile_id = snapshot.document.profile_id, .keymap = "keymap.zig", .callbacks = callbacks, .files = files.items };
    var output: std.Io.Writer.Allocating = .init(a);
    try std.zon.stringify.serializeMaxDepth(manifest, .{}, &output.writer, 16);
    try ownedWrite(gpa, io, dir, "manifest.zon", output.written());
    // Return an independently owned manifest. Caller frees with std.zon.parse.free.
    const text = try a.dupeZ(u8, output.written());
    var diagnostics: std.zon.parse.Diagnostics = .{};
    defer diagnostics.deinit(gpa);
    return std.zon.parse.fromSliceAlloc(contract.Manifest, gpa, text, &diagnostics, .{});
}
fn ownedWrite(gpa: std.mem.Allocator, io: std.Io, dir: std.Io.Dir, path: []const u8, bytes: []const u8) !void {
    if (std.fs.path.dirname(path)) |parent| try dir.createDirPath(io, parent);
    var file = try dir.createFileAtomic(io, path, .{ .replace = false });
    defer file.deinit(io);
    try file.file.writeStreamingAll(io, bytes);
    try file.file.sync(io);
    file.link(io) catch |err| switch (err) {
        error.PathAlreadyExists => {
            const existing = try dir.readFileAlloc(io, path, gpa, .limited(4 * 1024 * 1024));
            defer gpa.free(existing);
            if (!std.mem.eql(u8, existing, bytes)) return error.ExportOwnershipConflict;
        },
        else => return err,
    };
}
