const std = @import("std");

pub const Published = struct { module: *std.Build.Module, helpers: *std.Build.Module, basic: *std.Build.Module, generator: *std.Build.Step.Compile, tests: *std.Build.Step, check: *std.Build.Step };

pub fn publish(b: *std.Build, root: std.Build.LazyPath, model: *std.Build.Module, optimize: std.builtin.OptimizeMode) Published {
    const target = b.graph.host;
    const helpers = b.addModule("keycode-helpers", .{
        .root_source_file = root.path(b, "src/core.zig"),
        .imports = &.{.{ .name = "layout-model", .module = model }},
    });
    const basic = b.createModule(.{
        .root_source_file = root.path(b, "keycodes/keycodes.zig"),
        .imports = &.{
            .{ .name = "layout-model", .module = model },
            .{ .name = "keycode-helpers", .module = helpers },
        },
    });
    const mod = b.addModule("zkeycodes", .{
        .root_source_file = root.path(b, "root.zig"),
        .imports = &.{
            .{ .name = "layout-model", .module = model },
            .{ .name = "keycode-helpers", .module = helpers },
            .{ .name = "base-keycodes", .module = basic },
        },
    });
    // Conversion runs on the host, including when targeting firmware.
    const exe = b.addExecutable(.{
        .name = "zkeycodes",
        .root_module = b.createModule(.{
            .root_source_file = root.path(b, "src/main.zig"),
            .target = b.graph.host,
            .optimize = optimize,
        }),
    });

    const run = b.addRunArtifact(exe);
    run.setCwd(root.path(b, "."));
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Run the converter").dependOn(&run.step);
    const convert = b.addRunArtifact(exe);
    convert.setCwd(root.path(b, "."));
    const input = b.option([]const u8, "infile", "Input HJSON file");
    const output = b.option([]const u8, "outfile", "Output Zig file");
    if (input != null and output != null) {
        convert.addArgs(&.{ input.?, output.? });
    } else if (b.args) |args| {
        convert.addArgs(args);
    }
    b.step("convert", "Explicitly convert one HJSON file").dependOn(&convert.step);

    // Source updates are reachable only through explicit regeneration.
    const update = b.addUpdateSourceFiles();
    var dir = std.Io.Dir.cwd().openDir(b.graph.io, root.path(b, "qmk_imports").getPath(b), .{ .iterate = true }) catch |err|
        std.debug.panic("Cannot read qmk_imports: {}", .{err});
    defer dir.close(b.graph.io);
    var names: std.ArrayList([]const u8) = .empty;
    var iter = dir.iterate();
    while (iter.next(b.graph.io) catch @panic("Cannot enumerate qmk_imports")) |entry| {
        if (entry.kind == .file and std.mem.endsWith(u8, entry.name, ".hjson"))
            names.append(b.allocator, b.dupe(entry.name)) catch @panic("Out of memory");
    }
    std.mem.sort([]const u8, names.items, {}, lessThan);
    const check = b.step("keycodes-check-generated", "Check committed generated keycodes without mutation");
    const compare = b.addSystemCommand(&.{"python3"});
    compare.addFileArg(root.path(b, "tools/check_generated.py"));
    compare.addDirectoryArg(root.path(b, "keycodes"));
    var exports: std.ArrayList(u8) = .empty;
    exports.appendSlice(b.allocator, "// Auto-generated by zkeycodes (zig build convert-all). Do not edit by hand.\n") catch @panic("Out of memory");
    for (names.items) |name| {
        const out_name = outputName(b, name);
        const generated = generate(b, exe, root.path(b, b.fmt("qmk_imports/{s}", .{name})), out_name);
        update.addCopyFileToSource(generated, root.path(b, b.fmt("keycodes/{s}", .{out_name})).getPath(b));
        compare.addArgs(&.{out_name});
        compare.addFileArg(generated);
        const stem = out_name[0 .. out_name.len - 4];
        const source = if (std.mem.eql(u8, stem, "keycodes")) "base-keycodes" else out_name;
        exports.appendSlice(b.allocator, b.fmt("pub const {s} = @import(\"{s}\");\n", .{ stem, source })) catch @panic("Out of memory");
    }
    update.addBytesToSource(exports.items, root.path(b, "keycodes/all.zig").getPath(b));
    const export_files = b.addWriteFiles();
    compare.addArg("all.zig");
    compare.addFileArg(export_files.add("all.zig", exports.items));
    check.dependOn(&compare.step);
    b.step("convert-all", "Explicitly regenerate committed keycodes").dependOn(&update.step);

    const generated_basic = fixture(b, root, exe, model, helpers, null, "keycodes_0.0.1_basic.hjson", "keycodes.zig");
    const us = fixture(b, root, exe, model, helpers, generated_basic, "keycodes_us_international_0.0.1.hjson", "us_international.zig");
    const german = fixture(b, root, exe, model, helpers, generated_basic, "keycodes_german_mac_iso_0.0.1.hjson", "german_mac_iso.zig");
    const test_step = b.step("keycodes-test", "Run keycode generation and label tests");
    const host_mod = b.createModule(.{ .root_source_file = root.path(b, "root.zig"), .target = target, .imports = &.{
        .{ .name = "layout-model", .module = model },
        .{ .name = "keycode-helpers", .module = helpers },
        .{ .name = "base-keycodes", .module = basic },
    } });
    for ([_]*std.Build.Module{ host_mod, exe.root_module }) |module|
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = module })).step);
    for ([_][]const u8{ "test_generation.zig", "test_labels.zig" }) |source| {
        const module = b.createModule(.{
            .root_source_file = root.path(b, source),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "layout-model", .module = model },
                .{ .name = "keycode-helpers", .module = helpers },
                .{ .name = "base-keycodes", .module = generated_basic },
                .{ .name = "test-us", .module = us },
                .{ .name = "test-german", .module = german },
            },
        });
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = module })).step);
    }
    return .{ .module = mod, .helpers = helpers, .basic = basic, .generator = exe, .tests = test_step, .check = check };
}

pub fn build(b: *std.Build) void {
    _ = b.standardTargetOptions(.{});
    const published = publish(b, b.path("."), b.dependency("layout_model", .{}).module("layout-model"), b.standardOptimizeOption(.{}));
    b.installArtifact(published.generator);
    b.step("check-generated", "Check generated keycodes").dependOn(published.check);
    const tests = b.step("test", "Run keycode tests");
    tests.dependOn(published.tests);
    b.default_step = tests;
}

fn generate(b: *std.Build, exe: *std.Build.Step.Compile, input: std.Build.LazyPath, name: []const u8) std.Build.LazyPath {
    const run = b.addRunArtifact(exe);
    run.addFileArg(input);
    return run.addOutputFileArg(name);
}

fn fixture(b: *std.Build, root: std.Build.LazyPath, exe: *std.Build.Step.Compile, model: *std.Build.Module, helpers: *std.Build.Module, basic: ?*std.Build.Module, input: []const u8, name: []const u8) *std.Build.Module {
    const module = b.createModule(.{
        .root_source_file = generate(b, exe, root.path(b, b.fmt("test_data/{s}", .{input})), name),
    });
    module.addImport("layout-model", model);
    module.addImport("keycode-helpers", helpers);
    if (basic) |base| module.addImport("base-keycodes", base);
    return module;
}

fn outputName(b: *std.Build, name: []const u8) []const u8 {
    if (std.mem.indexOf(u8, name, "basic") != null) return "keycodes.zig";
    const after = if (std.mem.startsWith(u8, name, "keycodes_")) name[9..] else name;
    var end = after.len - 6;
    for (after, 0..) |c, i| {
        if (c == '_' and i + 1 < after.len and std.ascii.isDigit(after[i + 1])) {
            end = i;
            break;
        }
    }
    return b.fmt("{s}.zig", .{after[0..end]});
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}
