const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const zigmkay = b.dependency("zigmkay", .{}).module("zigmkay");
    const helpers = b.addModule("keycode-helpers", .{
        .root_source_file = b.path("src/core.zig"),
        .imports = &.{.{ .name = "zigmkay", .module = zigmkay }},
    });
    const basic = b.createModule(.{
        .root_source_file = b.path("keycodes/keycodes.zig"),
        .imports = &.{
            .{ .name = "zigmkay", .module = zigmkay },
            .{ .name = "keycode-helpers", .module = helpers },
        },
    });
    const mod = b.addModule("zkeycodes", .{
        .root_source_file = b.path("root.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "zigmkay", .module = zigmkay },
            .{ .name = "keycode-helpers", .module = helpers },
            .{ .name = "base-keycodes", .module = basic },
        },
    });
    // Conversion runs on the host, including when targeting firmware.
    const exe = b.addExecutable(.{
        .name = "zkeycodes",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = b.graph.host,
            .optimize = optimize,
        }),
    });
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    run.setCwd(b.path("."));
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Run the converter").dependOn(&run.step);
    const convert = b.addRunArtifact(exe);
    convert.setCwd(b.path("."));
    const input = b.option([]const u8, "infile", "Input HJSON file");
    const output = b.option([]const u8, "outfile", "Output Zig file");
    if (input != null and output != null) {
        convert.addArgs(&.{ input.?, output.? });
    } else if (b.args) |args| {
        convert.addArgs(args);
    }
    b.step("convert", "Explicitly convert one HJSON file").dependOn(&convert.step);

    // Source updates are reachable only through explicit regeneration.
    const update = b.addUpdateSourceFiles();
    var dir = b.build_root.handle.openDir("qmk_imports", .{ .iterate = true }) catch |err|
        std.debug.panic("Cannot read qmk_imports: {}", .{err});
    defer dir.close();
    var names: std.ArrayList([]const u8) = .empty;
    var iter = dir.iterate();
    while (iter.next() catch @panic("Cannot enumerate qmk_imports")) |entry| {
        if (entry.kind == .file and std.mem.endsWith(u8, entry.name, ".hjson"))
            names.append(b.allocator, b.dupe(entry.name)) catch @panic("Out of memory");
    }
    std.mem.sort([]const u8, names.items, {}, lessThan);
    var exports: std.ArrayList(u8) = .empty;
    exports.appendSlice(b.allocator, "// Auto-generated by zkeycodes (zig build convert-all). Do not edit by hand.\n") catch @panic("Out of memory");
    for (names.items) |name| {
        const out_name = outputName(b, name);
        const generated = generate(b, exe, b.path(b.fmt("qmk_imports/{s}", .{name})), out_name);
        update.addCopyFileToSource(generated, b.fmt("keycodes/{s}", .{out_name}));
        const stem = out_name[0 .. out_name.len - 4];
        const source = if (std.mem.eql(u8, stem, "keycodes")) "base-keycodes" else out_name;
        exports.appendSlice(b.allocator, b.fmt("pub const {s} = @import(\"{s}\");\n", .{ stem, source })) catch @panic("Out of memory");
    }
    update.addBytesToSource(exports.items, "keycodes/all.zig");
    b.step("convert-all", "Explicitly regenerate committed keycodes").dependOn(&update.step);

    const generated_basic = fixture(b, exe, zigmkay, helpers, null, "keycodes_0.0.1_basic.hjson", "keycodes.zig");
    const us = fixture(b, exe, zigmkay, helpers, generated_basic, "keycodes_us_international_0.0.1.hjson", "us_international.zig");
    const german = fixture(b, exe, zigmkay, helpers, generated_basic, "keycodes_german_mac_iso_0.0.1.hjson", "german_mac_iso.zig");
    const test_step = b.step("test", "Run keycode generation and label tests");
    for ([_]*std.Build.Module{ mod, exe.root_module }) |module|
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = module })).step);
    for ([_][]const u8{ "test_generation.zig", "test_labels.zig" }) |source| {
        const module = b.createModule(.{
            .root_source_file = b.path(source),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "zigmkay", .module = zigmkay },
                .{ .name = "keycode-helpers", .module = helpers },
                .{ .name = "base-keycodes", .module = generated_basic },
                .{ .name = "test-us", .module = us },
                .{ .name = "test-german", .module = german },
            },
        });
        test_step.dependOn(&b.addRunArtifact(b.addTest(.{ .root_module = module })).step);
    }
}

fn generate(b: *std.Build, exe: *std.Build.Step.Compile, input: std.Build.LazyPath, name: []const u8) std.Build.LazyPath {
    const run = b.addRunArtifact(exe);
    run.addFileArg(input);
    return run.addOutputFileArg(name);
}

fn fixture(b: *std.Build, exe: *std.Build.Step.Compile, zigmkay: *std.Build.Module, helpers: *std.Build.Module, basic: ?*std.Build.Module, input: []const u8, name: []const u8) *std.Build.Module {
    const module = b.createModule(.{
        .root_source_file = generate(b, exe, b.path(b.fmt("test_data/{s}", .{input})), name),
    });
    module.addImport("zigmkay", zigmkay);
    module.addImport("keycode-helpers", helpers);
    if (basic) |base| module.addImport("base-keycodes", base);
    return module;
}

fn outputName(b: *std.Build, name: []const u8) []const u8 {
    if (std.mem.indexOf(u8, name, "basic") != null) return "keycodes.zig";
    const after = if (std.mem.startsWith(u8, name, "keycodes_")) name[9..] else name;
    var end = after.len - 6;
    for (after, 0..) |c, i| {
        if (c == '_' and i + 1 < after.len and std.ascii.isDigit(after[i + 1])) {
            end = i;
            break;
        }
    }
    return b.fmt("{s}.zig", .{after[0..end]});
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.order(u8, a, b) == .lt;
}
