// Copyright 2026 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
// Auto-generated by zkeycodes from QMK hjson keycode files
const localcore = @import("keycode-helpers");
const core = @import("layout-model");
const L_SFT = localcore.L_SFT;
const L_ALT = localcore.L_ALT;
const R_ALT = localcore.R_ALT;
const R_CTL = localcore.R_CTL;
const DEAD = localcore.DEAD;
pub const keycodes = @import("base-keycodes");

pub const QMK_PLOVER_KEYCODES_VERSION = "0.0.1";
pub const QMK_PLOVER_KEYCODES_VERSION_BCD = @as(c_int, 0x00000001);
pub const QMK_PLOVER_KEYCODES_VERSION_MAJOR = @as(c_int, 0);
pub const QMK_PLOVER_KEYCODES_VERSION_MINOR = @as(c_int, 0);
pub const QMK_PLOVER_KEYCODES_VERSION_PATCH = @as(c_int, 1);

//
// ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
// │   │Num│   │   │   │   │   │   │   │   │   │   │   │       │
// ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
// │     │ S │ T │ P │ H │   │ * │ F │ P │ L │ T │ D │   │     │
// ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
// │      │   │ K │ W │ R │   │   │ R │ B │ G │ S │ Z │        │
// ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
// │        │   │   │ A │ O │   │ E │ U │   │   │   │          │
// ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
// │    │    │    │                        │    │    │    │    │
// └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
//
pub const NUM = keycodes.kcf.N1;
pub const LS = keycodes.kcf.Q;
pub const LT = keycodes.kcf.W;
pub const LP = keycodes.kcf.E;
pub const LH = keycodes.kcf.R;
pub const STAR = keycodes.kcf.Y;
pub const RF = keycodes.kcf.U;
pub const RP = keycodes.kcf.I;
pub const RL = keycodes.kcf.O;
pub const RT = keycodes.kcf.P;
pub const RD = keycodes.kcf.LBRC;
pub const LK = keycodes.kcf.S;
pub const LW = keycodes.kcf.D;
pub const LR = keycodes.kcf.F;
pub const RR = keycodes.kcf.J;
pub const RB = keycodes.kcf.K;
pub const RG = keycodes.kcf.L;
pub const RS = keycodes.kcf.SCLN;
pub const RZ = keycodes.kcf.QUOT;
pub const A = keycodes.kcf.C;
pub const O = keycodes.kcf.V;
pub const E = keycodes.kcf.N;
pub const U = keycodes.kcf.M;

// Label lookup table
pub const _labels = [_]localcore.LabelEntry{
    .{ .value = NUM, .label = "NUM", .short_label = "NUM" },
    .{ .value = LS, .label = "LS", .short_label = "LS" },
    .{ .value = LT, .label = "LT", .short_label = "LT" },
    .{ .value = LP, .label = "LP", .short_label = "LP" },
    .{ .value = LH, .label = "LH", .short_label = "LH" },
    .{ .value = STAR, .label = "STAR", .short_label = "STAR" },
    .{ .value = RF, .label = "RF", .short_label = "RF" },
    .{ .value = RP, .label = "RP", .short_label = "RP" },
    .{ .value = RL, .label = "RL", .short_label = "RL" },
    .{ .value = RT, .label = "RT", .short_label = "RT" },
    .{ .value = RD, .label = "RD", .short_label = "RD" },
    .{ .value = LK, .label = "LK", .short_label = "LK" },
    .{ .value = LW, .label = "LW", .short_label = "LW" },
    .{ .value = LR, .label = "LR", .short_label = "LR" },
    .{ .value = RR, .label = "RR", .short_label = "RR" },
    .{ .value = RB, .label = "RB", .short_label = "RB" },
    .{ .value = RG, .label = "RG", .short_label = "RG" },
    .{ .value = RS, .label = "RS", .short_label = "RS" },
    .{ .value = RZ, .label = "RZ", .short_label = "RZ" },
    .{ .value = A, .label = "A", .short_label = "A" },
    .{ .value = O, .label = "O", .short_label = "O" },
    .{ .value = E, .label = "E", .short_label = "E" },
    .{ .value = U, .label = "U", .short_label = "U" },
};

pub fn getLabel(keycode: core.KeyCodeFire, shortest: bool) ?[]const u8 {
    return localcore.getLabel(&_labels, keycode, shortest);
}
