//! LK7 schematic geometry in key units, not mechanical measurements.
//! IDs are explicit and remain stable when geometry or GPIO assignments change.
const model = @import("layout-model");
pub const keys = [_]model.physical_layout.Key{
    .{ .id = 0x100, .key_index = 0, .x = 0, .y = 0, .hand = .left, .group = .finger },
    .{ .id = 0x101, .key_index = 1, .x = 1, .y = 0, .hand = .left, .group = .finger },
    .{ .id = 0x102, .key_index = 2, .x = 2, .y = 0, .hand = .left, .group = .finger },
    .{ .id = 0x103, .key_index = 3, .x = 3, .y = 0, .hand = .left, .group = .finger },
    .{ .id = 0x104, .key_index = 4, .x = 4, .y = 0, .hand = .left, .group = .finger },
    .{ .id = 0x200, .key_index = 5, .x = 7, .y = 0, .hand = .right, .group = .finger },
    .{ .id = 0x201, .key_index = 6, .x = 8, .y = 0, .hand = .right, .group = .finger },
    .{ .id = 0x202, .key_index = 7, .x = 9, .y = 0, .hand = .right, .group = .finger },
    .{ .id = 0x203, .key_index = 8, .x = 10, .y = 0, .hand = .right, .group = .finger },
    .{ .id = 0x204, .key_index = 9, .x = 11, .y = 0, .hand = .right, .group = .finger },
    .{ .id = 0x105, .key_index = 10, .x = 0, .y = 1, .hand = .left, .group = .finger },
    .{ .id = 0x106, .key_index = 11, .x = 1, .y = 1, .hand = .left, .group = .finger },
    .{ .id = 0x107, .key_index = 12, .x = 2, .y = 1, .hand = .left, .group = .finger },
    .{ .id = 0x108, .key_index = 13, .x = 3, .y = 1, .hand = .left, .group = .finger },
    .{ .id = 0x109, .key_index = 14, .x = 4, .y = 1, .hand = .left, .group = .finger },
    .{ .id = 0x205, .key_index = 15, .x = 7, .y = 1, .hand = .right, .group = .finger },
    .{ .id = 0x206, .key_index = 16, .x = 8, .y = 1, .hand = .right, .group = .finger },
    .{ .id = 0x207, .key_index = 17, .x = 9, .y = 1, .hand = .right, .group = .finger },
    .{ .id = 0x208, .key_index = 18, .x = 10, .y = 1, .hand = .right, .group = .finger },
    .{ .id = 0x209, .key_index = 19, .x = 11, .y = 1, .hand = .right, .group = .finger },
    .{ .id = 0x10a, .key_index = 20, .x = 0, .y = 2, .hand = .left, .group = .finger },
    .{ .id = 0x10b, .key_index = 21, .x = 1, .y = 2, .hand = .left, .group = .finger },
    .{ .id = 0x10c, .key_index = 22, .x = 2, .y = 2, .hand = .left, .group = .finger },
    .{ .id = 0x10d, .key_index = 23, .x = 3, .y = 2, .hand = .left, .group = .finger },
    .{ .id = 0x10e, .key_index = 24, .x = 4, .y = 2, .hand = .left, .group = .finger },
    .{ .id = 0x20a, .key_index = 25, .x = 7, .y = 2, .hand = .right, .group = .finger },
    .{ .id = 0x20b, .key_index = 26, .x = 8, .y = 2, .hand = .right, .group = .finger },
    .{ .id = 0x20c, .key_index = 27, .x = 9, .y = 2, .hand = .right, .group = .finger },
    .{ .id = 0x20d, .key_index = 28, .x = 10, .y = 2, .hand = .right, .group = .finger },
    .{ .id = 0x20e, .key_index = 29, .x = 11, .y = 2, .hand = .right, .group = .finger },
    .{ .id = 0x180, .key_index = 30, .x = 3, .y = 3.25, .hand = .left, .group = .thumb },
    .{ .id = 0x181, .key_index = 31, .x = 4, .y = 3.25, .hand = .left, .group = .thumb },
    .{ .id = 0x280, .key_index = 32, .x = 7, .y = 3.25, .hand = .right, .group = .thumb },
    .{ .id = 0x281, .key_index = 33, .x = 8, .y = 3.25, .hand = .right, .group = .thumb },
};
